version: '3.8'

services:
  registry:
    image: registry:2
    container_name: private-registry
    ports:
      - "5001:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/cert-docker.crt
      REGISTRY_HTTP_TLS_KEY: /certs/cert-docker.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ./certs:/certs
      - ./auth:/auth
      - registry-data:/var/lib/registry

volumes:
  registry-data:
